### PR TITLE
Chore: update readme to link to cachified-redis-json-adapter

### PR DESCRIPTION
**Pull request by tearingItUp786**
[Issue link describing the request](https://github.com/Xiphe/cachified/issues/45)

Update the readme to link to [`cachified-redis-json-adapter`](https://www.npmjs.com/package/cachified-redis-json-adapter)

### CODE REVIEW

**Comment by Xiphe** [comment]
The whitespace changes seem odd to me. Prettier doesn't produces those locally on my end.

**Comment by tearingItUp786** [comment]
> The whitespace changes seem odd to me. Prettier doesn't produces those locally on my end.

Yeah... thought it was strange too. Will try again 😅

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
This is great! Thank you!

**Pull request merged**
